class Code {
  static const int oK = 0;
  static const int internalError = -1; // 内部错误
  static const int serviceError = -2; // 服务错误
  static const int notAuthenticated = -3; // 不允许操作, 未授权, 1244
  static const int noSuchUser = -4; // 没有此用户, 1317
  static const int userExists = -5; // 用户已存在, 1316
  static const int memberInGroup = -6; // 用户已经在组中, 1320
  static const int memberNotInGroup = -7; // 用户不在组中, 1321
  static const int logonFailure = -8; // 用户名或者密码错误, 1326
  static const int accountDisable = -9; // 帐号已被冻结, 不允许登录; 1331
  static const int noUserSessionKey = -10; // 没有会话密钥, 或者密钥已过期; 1394
  static const int notLoggedOn = -11; // 不允许操作, 帐号未授权; 1245
  static const int userProfileLoad = -12; // 无法加载用户详情; 500
  static const int passwordTooShort = -13; // 密码太短, 不符合规范; 615
  static const int passwordTooRecent = -14; // 修改密码过于频繁; 616
  static const int passwordTooLong = -15; // 密码太长, 不符合规范; 657
  static const int accountExpired = -16; // 帐号已过期, 无法使用; 1793
  static const int passwordMustChange = -17; // 强制重置密码, 重置密码后才允许登录; 1907
  static const int badUserName = -18; // 用户名错误, 不合法的用户名; 2202
  static const int networkBusy = -19; // 网络繁忙, 稍后再试; 54
  static const int unexpectedNetworkError = -20; // 未知网络错误; 59
  static const int networkAccessDenied = -21; // 网络访问被拒; 65
  static const int noNetwork = -22; // 没有网络; 1222
  static const int gracefulDisconnect = -23; // 网络连接已断开; 1226
  static const int connectionRefuse = -24; // 服务器拒绝网络连接; 1225
  static const int networkUnreachable = -25; // 网络不可到达; 1231
  static const int connectionAborted = -26; // 本机终止网络连接; 1236
  static const int incorrectAddress = -27; // 地址不正确, 无法使用; 1241
  static const int invalidData = -28; // 数据错误; 13
  static const int noData = -29; // 没有数据; 232
  static const int invalidToken = -30; // 无法识别、格式错误 或者 非法的token; 315
  static const int dataChecksumError = -31; // 数据检验失败; 323
  static const int databaseDoesNotExist = -32; // 数据库不存在; 1065
  static const int badConfiguration = -33; // 配置无效或者非法; 1610
  static const int unsupportedType = -34; // 不支持的数据类型; 1630
  static const int invalidDataType = -35; // 提供的数据类型无法识别 或者 非法的; 1804
  static const int resourceDataNotFound = -36; // 未找到资源, 如 图片无法找到; 1812
  static const int databaseFailure = -37; // 数据操作失败, 不能读写数据库; 4313
  static const int databaseFull = -38; // 数据库已满负载; 4314
  static const int appDataNotFound = -39; // 找不到应用程序的cache数据; 4400
  static const int appDataExpired = -40; // 应用程序的cache数据已超时; 4401
  static const int appDataCorrupt = -41; // 应用程序的cache数据已被损坏; 4402
  static const int appDataLimitExceeded = -42; // 应用程序的cache数据超出预留空间; 4403
  static const int badTokenType = -43; // token可被系统识别, 但用途错误, 当前应用无法使用; 1349
  static const int tokenAlreadyInUse = -44; // token已被使用 或者 占用; 1375
  static const int invalidTime = -45; // 时间格式错误, 是无效 或者 非法的; 1901
  static const int dataSourceProtocolError = -46; // 数据源协议错误; 8225
  static const int notSupported = -47; // 不支持的请求, 无法处理请求; 50
  static const int busy = -48; // 请求的资源已被占用; 170
  static const int requestAborted = -49; // 请求被中止; 1235
  static const int noToken = -50; // 请求协议中没有提供token; 1008
  static const int invalidEncryptAlgorithm = -51; // 非法的加密算法; 13873
  static const int encryptingPayloadFailure = -52; // 加密payload失败; 13866
  static const int decryptingPayloadFailure = -53; // 解密payload失败; 13867
  static const int invalidCertificateSignature = -54; // 非法的签名, 签名无法被应用识别; 13875
  static const int unHandledException = -55; // 程序存在未处理异常; 574
  static const int serviceRequestTimeout = -56; // 服务器处理请求超时; 1053
  static const int objectAlreadyExists = -57; // 对象已存在 或者 已被占用; 5010
  static const int objectInList = -58; // 对象已存在于列表中; 5011
  static const int notConnected = -59; // 网络连接不存在, 网络未连接; 2250
  static const int entryNotFound = -60; // 找不到Entry; 1761
  static const int entryAlreadyExists = -61; // Entry已存在, 或者被占用; 1760
  static const int missingData = -62; // 请求的数据不在缓存中, 缓存中未找到相应数据; 4052
  static const int notInitialized = -63; // 提供的对象未初始化;4054
  static const int alreadyInitialized = -64; // 提供的对象已完成初始化; 4055
  static const int alreadyCompleted = -65; // 操作已完成; 4060
  static const int accessDenied = -66; // 未授权, 拒绝访问; 5
  static const int empty = -67; // 为空, 没有值; 4306
  static const int notEmpty = -68; // 不为空, 有值; 4307
}
