import 'package:flutter_framework/common/translator/language.dart';

class Chinese {
  static const String _name = 'Chinese';
  static Map<String, String> model = {
    Language.titleOfSearch: '查询',
    Language.reset: '重置',
    Language.userList: '用户列表',
    Language.fPhoneNumber: '手机号码',
    Language.fCountryCode: '国家地区码',
    Language.fName: '姓名',
    Language.fStatus: '状态',
    Language.fCreatedAt: '创建时间',
    Language.roleList: '角色列表',
    Language.permissionList: '权限列表',
    Language.menuList: '菜单列表',
    Language.operation: '操作',
    Language.newUser: '新增用户',
    Language.cancel: '取消',
    Language.confirm: "确定",
    Language.enable: '启用',
    Language.disable: '停用',
    Language.china: '中国',
    Language.philipine: '菲律宾',
    Language.password: '密码',
    Language.confirmPassword: '确认密码',
    Language.modifyUser: '更新用户资料',
    Language.dashboard: '通用后台管理系统',
    Language.ok: '确定',
    Language.viewPermissionList: '查看权限列表',
    Language.viewMenuList: '查看菜单列表',
    Language.viewRoleList: '查看角色列表',
    Language.removeUser: '删除用户',
    Language.update: '更新',
    Language.remove: '删除',
    Language.confirmYourDeletion: '确认删除?',
    Language.titleOfPermission: '权限',
    Language.major: '主业务号',
    Language.minor: '次业务号',
    Language.subMenu: '菜单',
    Language.titleOfOperator: '操作人',
    Language.request: '请求',
    Language.response: '应答',
    Language.operationTimestamp: '操作时间',
    Language.operationLog: '操作日志列表',
    Language.fieldList: '字段列表',
    Language.tMenu: '菜单',
    Language.titleOfBeginDate: '开始日期',
    Language.titleOfEndDate: '结束日期',

    // language
    Language.languageOfChinese: '简体中文',
    Language.languageOfEnglish: '英文',

    // common
    Language.description: '描述',
    Language.valueOfNull: '',
    Language.loading: "加载中",
    Language.clickToView: "点击查看",

    // menu
    Language.titleOfParentMenu: '父级菜单',
    Language.menuOfAdmission: '系统管理',
    Language.menuOfUser: '用户管理',
    Language.menuOfRole: '角色管理',
    Language.menuOfField: '字段管理',
    Language.menuOfMenu: '菜单管理',
    Language.menuOfPermission: '权限管理',
    Language.menuOfTrack: '操作日志',

    // field
    Language.tableOfField: '数据表',
    Language.nameOfField: '字段',
    Language.userOfTable: 'user',
    Language.idOfUser: 'id',
    Language.descriptionOfIdOfUser: '用户ID',
    Language.nameOfUser: 'name',
    Language.descriptionOfNameOfUser: '姓名',
    Language.countryCodeOfUser: 'country_code',
    Language.descriptionOfCountryCodeOfUser: '国家地区码',
    Language.phoneNumberOfUser: 'phone_number',
    Language.descriptionOfPhoneNumberOfUser: '电话号码',
    Language.statusOfUser: 'status',
    Language.descriptionOfStatusOfUser: '状态',
    Language.createdAtOfUser: 'created_at',
    Language.descriptionOfCreatedAtOfUser: '创建日期',

    // permission
    Language.signIn: '登入系统',
    Language.fetchMenuListOfCondition: '获取菜单列表',
    Language.fetchUserListOfCondition: '获取用户列表',
    Language.fetchRoleListOfCondition: '获取角色列表',
    Language.fetchPermissionListOfCondition: '获取权限列表',
    Language.insertUserRecord: '新增用户',
    Language.softDeleteUserRecord: '删除用户',
    Language.updateUserRecord: '更新用户',
    Language.managementOfUsers: '用户管理',
    Language.managementOfRoles: '角色管理',
    Language.managementOfMenus: '菜单管理',
    Language.managementOfPermissions: '权限管理',
    Language.managementOfFields: '字段管理',
    Language.managementOfTracks: '日志管理',

    // role
    Language.titleOfRole: '角色',
    Language.rankOfRole: '级别',
    Language.departmentOfRole: '部门',
    Language.administrator: '系统管理员',
    Language.rdManager: '研发部主管',
    Language.softwareEngineer: '软件工程师',
    Language.hardwareEngineer: '硬件工程师',
    Language.financeManger: '财务部主管',
    Language.purchasingSpecialist: '采购专员',
    Language.accountingSpecialist: '财务专员',
    Language.hrManger: '人事部主管',
    Language.hrSpecialist: '人事行政专员',
    Language.marketingManger: '市场部主管',
    Language.salesSpecialist: '销售专员',
    Language.manufacturingManger: '生产部主管',
    Language.productionSpecialist: '生产线专员',
    Language.descriptionOfAdministrator: '董事会主席',
    Language.descriptionOfRDManager: '研发部负责人，管理 软件与硬件 相关职能',
    Language.descriptionOfSoftwareEngineer: '研发部门-软件工程师',
    Language.descriptionOfHardwareEngineer: '研发部门-硬件工程师',
    Language.descriptionOfFinanceManger: '财务部门负责人',
    Language.descriptionOfPurchasingSpecialist: '财务部门-采购专员',
    Language.descriptionOfAccountingSpecialist: '财务部门-会计专员',
    Language.descriptionOfHRManger: '人事部门负责人',
    Language.descriptionOfHRSpecialist: '人事部-人事行政专员',
    Language.descriptionOfMarketingManger: '市场部负责人',
    Language.descriptionOfSalesSpecialist: '市场部-销售专员',
    Language.descriptionOfManufacturingManger: '生产部门负责人',
    Language.descriptionOfProductionSpecialist: '生产部-生产线专员',
    Language.departmentOfBoardOfDirectors: '董事会',
    Language.departmentOfResearchAndDevelopment: '研发部',
    Language.departmentOfFinanceDepartment: '财务部',
    Language.departmentOfHumanResourcesDepartment: '人事部',
    Language.departmentOfMarketingDepartment: '市场部',
    Language.departmentOfManufacturingDepartment: '生产部',

    // dialog
    Language.titleOfErrorNotifyDialog: '错误提示',
    Language.passwordInTwoInputControlDoNotMatch: '两次输入的密码不一致',
    Language.titleOfNotification: '温馨提醒: ',
    Language.messageOfSomewhereLogin: '您的帐号已在别处登录.',
    Language.endDateIsBeforeBeginDate: '结束日期在开始日期之前',
    Language.failureOnFetchMenuListOfCondition: '获取菜单数据失败',
    Language.noDataFailureOnFetchMenuListOfCondition: '没有菜单数据',
    Language.accessDeniedFailureOnFetchPermissionOfCondition: '拒绝访问',
    Language.failureWithErrorCode: '错误代码: ',
    Language.failureWithoutErrorCode: '程序异常',
    Language.networkDisconnected: '网络已断开',
    Language.networkConnected: '网络已连接',
    Language.buyingPriceNotProvided: "未提供进货价",
    Language.productNameNotProvided: "未提供商品名称",
    Language.removeRecordSuccessfully: '删除成功',
    Language.updateRecordSuccessfully: '更新成功',

    // inform.notification
    Language.eventForceOffline: '强制下线',
    Language.messageForceOffline: '帐号在异地登录, 当前帐号被强制下线.',

    // Operations
    Language.operations: '运营管理',
    Language.good: '商品',
    Language.category: "类目",
    Language.advertisement: '广告',
    Language.idOfGood: '商品ID',
    Language.nameOfGood: '商品名称',
    Language.listOfGoods: '商品列表',
    Language.importGood: "录入商品",
    Language.buyingPrice: "进货价",
    Language.vendorOfGood: "供应商",
    Language.statusOfGood: "状态",
    Language.contactOfVendor: "联系方式",
    Language.idOfAdvertisement: "广告ID",
    Language.nameOfAdvertisement: "广告名称",
    Language.listOfAdvertisements: "广告列表",
    Language.titleOfAdvertisement: "销售标语",
    Language.sellingPriceOfAdvertisement: "出售价格",
    Language.placeOfOriginOfAdvertisement: "产地",
    Language.sellingPointsOfAdvertisement: "卖点",
    Language.stockOfAdvertisement: "库存",
    Language.urlOfAdvertisement: "图片路径",
    Language.newAdvertisement: "新增广告",
    Language.modifyGood: "更新商品信息",
    Language.peekInfoFromProductId: "查看商品信息",
    Language.productIdIsEmpty: "商品ID为空",
    Language.withoutProductInfoInResponse: "未找到商品信息",
    Language.nameOfAdvertisementIsEmpty: "未提供广告名称",
    Language.addSellingPointToAdvertisement: "添加商品卖点",
    Language.fillSellingPoint: "请输入商品卖点",
    Language.pressRightButtonToAddSellingPoint: "点击右则按钮增加商品卖点",
    Language.incorrectStockValueInController: "库存设定有误",
    Language.incorrectSellingPriceInController: "出售价格有误",
    Language.needToPeekProductInfo: "请先确认商品信息",
    Language.modifyAdvertisement: "更新广告",
    Language.noRecordOfGoodInDatabase: "数据库没有任何商品记录",
    Language.noRecordsMatchedTheSearchCondition :"未找到匹配记录",
  };

  static String getName() {
    return _name;
  }

  static String translate(String input) {
    if (model.containsKey(input)) {
      return model[input]!;
    } else {
      return 'Unknown input: $input';
    }
  }
}
